---
# tasks file for oss_update
- name: create option 1 update python script
  template:
    src: oss_pack_update_2.j2
    dest: roles/oss_update/files/.{{ todays_date }}_{{ oss_pack_version }}_oss_pack_update_2.py
  when: update_method == '1'

- name: run option 1 update python script
  command: python3 .{{ todays_date }}_{{ oss_pack_version }}_oss_pack_update_2.py
  args:
    chdir: roles/oss_update/files
  with_first_found: site.yml
  delegate_to: localhost
  when: update_method == '1'
  run_once: true
  register: python_result_1

- debug:
    var: python_result_1
  when: update_method == '1'

- name: create option 2 update python script
  template:
    src: oss_pack_update_2_batch.j2
    dest: roles/oss_update/files/.{{ csv_batch_file }}_{{ oss_pack_version }}_oss_pack_update_2_batch.py
  when: update_method == '2'

- name: run option 2 update python script
  command: python3 .{{ csv_batch_file }}_{{ oss_pack_version }}_oss_pack_update_2_batch.py
  args:
    chdir: roles/oss_update/files
  with_first_found: site.yml
  delegate_to: localhost
  when: update_method == '2'
  run_once: true
  register: python_result_2

- debug:
    var: python_result_2
  when: update_method == '2'
